### ISSUE TITLE
Equality constraints - partial update of P and A?

### ISSUE THREAD

**Issue by micaelli** [oxfordcontrol/miosqp#3]
Would it be possible:
- to efficiently include equality constraints ? (rather than solving them or including:  0<= Cx + d <=0) 
- to "online" partially modifiy P and A ? (rather than defining a new problem each step ,e.g. for control)

best regards
Alain

**Comment by goulart-paul** [comment]
Regarding the two points below:

1) We only support equality constraints in the indirect sense that one can set the left and right hand sides of the inequality

l \le Ax \le u

to each other, i.e. l = u (or some subset thereof).   Doing it this way turns out not really to be any less efficient than handling equality constraints as a special case.   You might argue that the two sides are redundant and therefore memory inefficient, but this is not that much of a concern typically because the extra space requirement is linear in the number of constraints, and typically these are not the main drivers of memory use.

2) OSQP allows one to update the matrix-valued parameters, but not miOSQP (though it could easily be upgraded to do so).   The miOSQP wrapper only supports online modification to the linear terms (i.e. q, l, u).

However, if you are doing this for something like predictive control then typically the parameter that is updated online is the system initial state, which is one of the linear terms, so you should still be able to do so.

PG

**Comment by micaelli** [comment]
Thanks Paul for your quick answer. Actually I am doing predictive control, but if I can manage without changing P, I need modifying a part of A at each prediction step; in fact, the system itself is changing.

Alain

**Comment by goulart-paul** [comment]
OK, understood.   As I said, it is possible to do what you want within OSQP since we allow changes to A and P as well, but note that this will slow the solver down a bit because it means you will require a refactorization.

The miOSQP wrapper only supports changes to (q,l,u), but I don’t see any reason in principle why it could not be modified slightly to allow changes to A and P as well.

**Comment by micaelli** [comment]
Ok, thanks Paul, I'll try this. I was just afraid of possible side effects... P and/or  Q modifications must be correctly reported in miOsqp as well. I hope I won't forget something. However... let's try and see what happens.    

Alain
